frase = 'Curso em Vídeo Python'
print(frase[::2])

print("""Hi alansenairj,
We can’t connect to your Facebook Pages.
It could be because of an update you made, or improvements on the service’s end.
Click through to fix it.""" )

print(frase.upper().count('o'))

print(len(frase.strip()))
print(frase.replace('Python', 'Buceta'))
print(frase)
frase = frase.replace('Curso','Pornô de ' )
print(frase)
print(frase.find('Curso'))
print(frase.lower().find('Vídeo'))
print(frase.split())
frase = 'Curso em Vídeo Python'
dividido = frase.split()
print(dividido[2][3])



